language: node_js
node_js:
  - 12.1
services:
  - xvfb
addons:
  chrome: stable
before_install:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install
scripts:
  - npm test
after_success:
  - npm run codecov